GameStore 2.0/Controllers/CartController.cs
using GameStore_2._0.Models.Reps;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace GameStore_2._0.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IGamesRepository _gameRepository;
        private readonly ICartsRepository _cartRepository;
        public CartController(IGamesRepository gameRepository, ICartsRepository cartRepository)
        {
            _gameRepository = gameRepository;
            _cartRepository = cartRepository;
        }
        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(_cartRepository.GetByUserId(userId));
        }
        public IActionResult AddToCart(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _cartRepository.AddToCart(id, userId);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult AddToCartAjax(int id)
        { 
            if (User.Identity.IsAuthenticated == false)
            {
                return Json(new { success = false, message = "Вы должны войти в аккаунт." });
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _cartRepository.AddToCart(id, userId);
            return Json(new { success = true });
        }
        public IActionResult RemoveFromCart(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var game = _gameRepository.GetById(id);
            _cartRepository.RemoveFromCart(game, userId);
            return RedirectToAction("Index");
        }
        public IActionResult ClearCart()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _cartRepository.ClearCart(userId);
            return RedirectToAction("Index");
        }
    }
}

GameStore 2.0/Controllers/GameController.cs
using GameStore_2._0.Models;
using GameStore_2._0.Models.Reps;
using Microsoft.AspNetCore.Mvc;

namespace GameStore_2._0.Controllers
{
    public class GameController : Controller
    {
        private readonly IGamesRepository _gameRepository;
        public GameController(IGamesRepository gameRepository)
        {
            _gameRepository = gameRepository;
        }
        public IActionResult Index(int id)
        {
            var game = _gameRepository.GetById(id);
            if (game == null)
            {
				return RedirectToPage("/Error", new { errorMessage = "Такой игры нет." });
			}
            _gameRepository.ClickCountIncrement(id);
            return View(game);
        }
    }
}

GameStore 2.0/Controllers/OrderController.cs
using GameStore_2._0.Models;
using GameStore_2._0.Models.Reps;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using GameStore_2._0.DBModels;

namespace GameStore_2._0.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrdersRepository _ordersRepository;
        private readonly ICartsRepository _cartsRepository;
        private readonly UserManager<User> _userManager;

        public OrderController(IOrdersRepository ordersRepository, ICartsRepository cartsRepository, UserManager<User> userManager)
        {
            _ordersRepository = ordersRepository;
            _cartsRepository = cartsRepository;
            _userManager = userManager;
        }

        public IActionResult Create()
        {
            var user = _userManager.GetUserAsync(User).Result;
            var cart = _cartsRepository.GetByUserId(user.Id);
            if (cart == null || !cart.Positions.Any())
            {
                return RedirectToPage("/Error", new { errorMessage = "Корзина пуста." });
            }

            var order = new OrderVM(cart, User.FindFirst(ClaimTypes.Email).Value, _userManager.GetUserAsync(User).Result.PhoneNumber, user.Id, cart.CartCost);
            user.BuySum += cart.CartCost;
            _ordersRepository.Add(order);


            _cartsRepository.ClearCart(user.Id);
            return View();
        }
        public IActionResult GetOrders()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var orders = _ordersRepository.GetByUserId(userId);
            return View(orders);
        }
    }
}

GameStore 2.0/Views/Cart/Index.cshtml
@model CartVM

<div class="container text-center russo-one mt-2" style="color: blanchedalmond;">
    <h2>Корзина</h2>
</div>

@if (Model == null || Model.Positions.Count == 0)
{
    <div class="container mt-4 mb-4 w-25 russo-one text-center">
        <h4>Корзина пуста</h4>
        <a role="button" class="btn btn-dark button1" asp-controller="Home" asp-action="Index">На главную</a>
    </div>
}
else
{
    <div class="container mt-3">
        <table class="table table-dark my_table text-center">
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Количество</th>
                    <th>Цена за единицу</th>
                    <th>Добавить / убрать</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var position in Model.Positions)
                {
                    <tr>
                        <td>
                            <a asp-controller="Game" asp-action="Index" asp-route-id="@position.Game.Id">@position.Game.Title</a>  
                        </td>
                        <td>@position.Amount</td>
                        <td>@position.Game.Price руб.</td>
                        <td class="h5">
                            <a asp-controller="Cart" asp-action="AddToCart" asp-route-id="@position.Game.Id">+</a>
                            <a asp-controller="Cart" asp-action="RemoveFromCart" asp-route-id="@position.Game.Id">-</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="container mt-3">
        <h4 class="text-center my_text">Итого c учетом скидки (@Model.UserDiscount %): @Model.CartCost руб.</h4>
    </div>

    <div class="container text-center mb-4 mt-3">
        <a role="button" class="btn btn-dark button1" asp-controller="Order" asp-action="Create">Оформить заказ</a>
        <a role="button" class="btn btn-dark button1" asp-controller="Cart" asp-action="ClearCart">Очистить корзину</a>
        <a role="button" class="btn btn-dark button1" asp-controller="Home" asp-action="Index">На главную</a>
    </div>
}